### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ddrinan** [eriqande/gsi_sim#3]
Eric,

Hi, really excited about using gsi_sim with assigner. I'm curious if you've ever run into any compilation issues? I got the following errors. It has been a LONG time since I've written anything in C, so looking at the source code didn't help me. Any ideas? I'm using gcc v5.4.0 on Ubuntu 16.04.

Thanks,
Dan

dan@merlab:~/Desktop/gsi_sim$ ./Compile_gsi_sim.sh 
Compiling up executable gsi_sim-Linux

./eca-shared/ecalibs/ECA_ReadData.c: In function ‘erdOpenFileOrRetry’:
./eca-shared/ecalibs/ECA_ReadData.c:252:3: warning: ignoring return value of ‘scanf’, declared with attribute warn_unused_result [-Wunused-result]
   scanf("%s",F);
   ^
./eca-shared/ecalibs/MathStatRand.c: In function ‘SeedFromFile’:
./eca-shared/ecalibs/MathStatRand.c:1299:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(sfile,"%ld %ld",&seed1,&seed2);
   ^
./eca-shared/ecalibs/MathStatRand.c: In function ‘QuietSeedFromFile’:
./eca-shared/ecalibs/MathStatRand.c:1319:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(sfile,"%ld %ld",&seed1,&seed2);
   ^
./src/gsi_sim.c: In function ‘SlurpPostPredRanFile’:
./src/gsi_sim.c:322:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(in," %d", &junk);
   ^
./src/gsi_sim.c:330:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(in," %d", &(ret[i]));
   ^
./src/gsi_sim.c: In function ‘ReadIndsFromFile’:
./src/gsi_sim.c:2544:2: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(in," %d %d", &NumInds,&NumLoc);
  ^
./src/gsi_sim.c:2552:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(in," %s",temp);
   ^
./src/gsi_sim.c:2554:4: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
    fscanf(in," %d",&ploid);
    ^
./src/gsi_sim.c:2556:4: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
    fscanf(in," %s",temp); /* then scan for locus name */
    ^
./src/gsi_sim.c:2570:2: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(in," %s",temp);
  ^
./src/gsi_sim.c:2573:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(in," %s",PN[NumPops]);
   ^
./src/gsi_sim.c:2599:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(in," %s",temp);
   ^
./src/gsi_sim.c:2602:4: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
    fscanf(in," %s",PN[NumPops]);
    ^
./src/gsi_sim.c:2628:6: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
      fscanf(in," %d",&a);
      ^
./src/gsi_sim.c: In function ‘ReadLocFile’:
./src/gsi_sim.c:3680:2: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(in,"%d",&(P[L]->NumLoc) );
  ^
./src/gsi_sim.c:3706:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(in,"%d",&(P[L]->NumAlle[j]));
   ^
./src/gsi_sim.c:3725:4: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
    fscanf(in,"%lf",&(P[L]->x[j][k]));
    ^
./src/gsi_sim.c: In function ‘GatherReportingUnitData’:
./src/gsi_sim.c:3856:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(file," %s",tempstr);
   ^
./src/gsi_sim.c:3896:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(file," %s",tempstr);
   ^
./src/gsi_sim.c:3903:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(file," %s",tempstr);
   ^
./src/gsi_sim.c:3919:4: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
    fscanf(file," %s",tempstr);
    ^

Successfully compiled the executable gsi_sim-Linux

**Comment by ddrinan** [comment]
Ha, part of the problem is clearly that I should be running ./gsi_sim-Linux (and not ./gsi_sim-Darwin like I did the first time). It seems to run when (or at least spit out help) when I run the linux command, but should I be concerned about the warnings while compiling?

Thanks, Dan

**Comment by eriqande** [comment]
Hi Dan,

Thanks for the note.  I am not too worried about these warnings.  (they are warnings rather than errors.)  What is happening there is that fscanf(), a function that reads input from a file stream, also returns a value to indicate whether it has been successful or not.  In my code I don't capture those return values into a variable.    On linux it apparently uses the `-Wunused-result` flag whilst compiling, so it tosses out a few warnings about this.  Nothing is broken though.

I hope it all works well for you.  Cheers,

eric
